### ISSUE TITLE
custom web browser home page

### ISSUE THREAD

**Issue by ghost** [ZenithDS/dotconfig#1]
Hi i would love if you can provide me with the custom web page that is on you screenshot, and i love the work you did on your system it looks gorgeous by the way and i didn't knew that macOS is customizable so good gob and what is that terminal program called that looks like htop, thank you.

**Comment by dotzenith** [comment]
Hey! I'm glad you like my config :) The browser home page is just an extension called [nightTab.](https://chrome.google.com/webstore/detail/nighttab/hdpcadigjkbcpnlcpbcohpafiaefanki?hl=en-GB) As for the terminal command you're referring to, it's called [bpytop.](https://github.com/aristocratos/bpytop)
