### ISSUE TITLE
compistor

### ISSUE THREAD

**Issue by evilja** [ZenithDS/dotconfig#2]
is compistor picom?

**Comment by dotzenith** [comment]
These dotfiles are for MacOS, and as such they're using the default MacOS compositor :)

**Comment by evilja** [comment]
uhh. can i use picom in gentoo?

26 May 2022 Per 21:00 tarihinde ZenithDS ***@***.***> şunu
yazdı:

**Comment by dotzenith** [comment]
I don't daily drive linux and I've never used gentoo but you can probably use picom on gentoo!!

**Comment by dotzenith** [comment]
Closing this but any discussion is welcomed :)
